# Generated by Django 5.0.7 on 2024-09-24 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("type_of_complain", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_logged", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ITSM_Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("priority", models.TextField()),
                ("status", models.TextField()),
                ("created_on", models.DateTimeField()),
                ("message_processor", models.TextField()),
                ("support_team_id", models.IntegerField()),
                ("support_team", models.TextField()),
                ("category_1", models.TextField()),
                ("category_2", models.TextField()),
                ("category_3", models.TextField()),
                ("ministry", models.TextField()),
                ("control_officer", models.TextField()),
                ("code_ptj", models.CharField(max_length=8)),
                ("last_changed_on", models.DateTimeField()),
                ("type_of_complain", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="KBA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knowledge_article_id", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("module", models.TextField()),
                ("keywords", models.TextField()),
                ("category_1", models.TextField()),
                ("category_2", models.TextField()),
                ("category_3", models.TextField()),
                ("issue", models.TextField()),
                ("resolution", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=14)),
                ("helpfulness_rating", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "knowledge_article_id",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
    ]
